/**
 * @file mock data
 */

export const province = [{
    name: '重庆市',
    children: [{
        name: '重庆一区',
        city: '重庆市',
        idc: 2,
        host: 31,
        sw: 14,
        health: 100,
        isWarning: false
    }]
},
{
    name: '安徽省',
    children: [{
        name: '安徽（合肥一区）',
        city: '合肥',
        idc: 3,
        host: 34,
        sw: 17,
        health: 100,
        isWarning: false
    }, {
        name: '临泉政务云',
        city: '阜阳',
        idc: 0,
        host: 20,
        sw: 16,
        health: 100,
        isWarning: false
    }, {
        name: '安徽（亳州一区）',
        city: '亳州',
        idc: 1,
        host: 9,
        sw: 12,
        health: 100,
        isWarning: false
    }]
}, {
    name: '陕西省',
    children: [{
        name: '陕西（西安三区）',
        city: '西安',
        idc: 2,
        host: 13,
        sw: 7,
        health: 100,
        isWarning: false
    }, {
        name: '陕西（西安二区）',
        city: '西安',
        idc: 2,
        host: 34,
        sw: 15,
        health: 100,
        isWarning: false
    }, {
        name: '陕西（西安一区）',
        city: '西安',
        idc: 1,
        host: 18,
        sw: 8,
        health: 100,
        isWarning: false
    }]
}, {
    name: '四川省',
    children: [{
        name: '天府云（眉山一区）',
        city: '眉山',
        idc: 0,
        host: 8,
        sw: 7,
        health: 100,
        isWarning: false
    }, {
        name: '四川（绵阳一区）',
        city: '绵阳',
        idc: 1,
        host: 0,
        sw: 7,
        health: 100,
        isWarning: false
    }, {
        name: '四川（成都一区）',
        city: '成都',
        idc: 2,
        host: 53,
        sw: 14,
        health: 100,
        isWarning: false
    }]
}, {
    name: '湖北省',
    children: [{
        name: '湖北（武汉一区）',
        city: '武汉',
        idc: 2,
        host: 58,
        sw: 14,
        health: 100,
        isWarning: false
    }]
}, {
    name: '河南省',
    children: [{
        name: '河南（郑州一区）',
        city: '郑州',
        idc: 2,
        host: 55,
        sw: 15,
        health: 80,
        isWarning: false
    }]
}, {
    name: '北京市',
    children: [{
        name: '北京长城网',
        city: '北京市',
        idc: 0,
        host: 36,
        sw: 0,
        health: 100,
        isWarning: false
    }, {
        name: '北京一区',
        city: '北京市',
        idc: 2,
        host: 294,
        sw: 50,
        health: 100,
        isWarning: false
    }, {
        name: '北龙云海（北京一区）',
        city: '北京市',
        idc: 0,
        host: 11,
        sw: 7,
        health: 100,
        isWarning: false
    }, {
        name: '湖北（三峡云）',
        city: '北京市',
        idc: 0,
        host: 8,
        sw: 3,
        health: 100,
        isWarning: false
    }, {
        name: '北京（世纪网源）',
        city: '北京市',
        idc: 0,
        host: 3,
        sw: 0,
        health: 100,
        isWarning: false
    }, {
        name: '北京国信新网',
        city: '北京市',
        idc: 0,
        host: 0,
        sw: 0,
        health: 100,
        isWarning: false
    }]
}, {
    name: '吉林省',
    children: [{
        name: '吉林（长春一区）',
        city: '长春',
        idc: 2,
        host: 15,
        sw: 15,
        health: 100,
        isWarning: false
    }]
}, {
    name: '江西省',
    children: [{
        name: '赣企云（南昌一区）',
        city: '南昌',
        idc: 0,
        host: 8,
        sw: 7,
        health: 100,
        isWarning: false
    }, {
        name: '江西（南昌一区）',
        city: '南昌',
        idc: 2,
        host: 21,
        sw: 15,
        health: 100,
        isWarning: false
    }]
}, {
    name: '山东省',
    children: [{
        name: '山东（德州一区）',
        city: '德州',
        idc: 1,
        host: 8,
        sw: 12,
        health: 100,
        isWarning: false
    }, {
        name: '山东（济南一区）',
        city: '济南',
        idc: 4,
        host: 36,
        sw: 15,
        health: 100,
        isWarning: false
    }, {
        name: '山东（青岛一区）',
        city: '青岛',
        idc: 2,
        host: 17,
        sw: 10,
        health: 100,
        isWarning: false
    }]
}, {
    name: '甘肃省',
    children: [{
        name: '甘肃（兰州一区）',
        city: '兰州',
        idc: 1,
        host: 22,
        sw: 15,
        health: 100,
        isWarning: false
    }]
}, {
    name: '广东省',
    children: [{
        name: '广电网络（广州一区）',
        city: '广州',
        idc: 0,
        host: 9,
        sw: 4,
        health: 100,
        isWarning: false
    }, {
        name: '广东（深圳二区）',
        city: '深圳',
        idc: 0,
        host: 169,
        sw: 44,
        health: 100,
        isWarning: false
    }, {
        name: '广东（东莞一区）',
        city: '东莞',
        idc: 2,
        host: 25,
        sw: 12,
        health: 100,
        isWarning: false
    }, {
        name: '广东（深圳一区）',
        city: '深圳',
        idc: 2,
        host: 42,
        sw: 12,
        health: 100,
        isWarning: false
    }, {
        name: '广东（深圳三区）',
        city: '深圳',
        idc: 1,
        host: 225,
        sw: 92,
        health: 100,
        isWarning: false
    }, {
        name: '广东（广州二区）',
        city: '广州',
        idc: 1,
        host: 38,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '广东（珠海一区）',
        city: '珠海',
        idc: 1,
        host: 7,
        sw: 5,
        health: 100,
        isWarning: false
    }, {
        name: '广东（汕头一区）',
        city: '汕头',
        idc: 0,
        host: 8,
        sw: 2,
        health: 100,
        isWarning: false
    }, {
        name: '广东（云峰一区）',
        city: '广州',
        idc: 1,
        host: 13,
        sw: 6,
        health: 100,
        isWarning: false
    }, {
        name: '广东（广州一区）',
        city: '广州',
        idc: 2,
        host: 476,
        sw: 139,
        health: 100,
        isWarning: false
    }, {
        name: '政务云（广州一区）',
        city: '广州',
        idc: 0,
        host: 0,
        sw: 7,
        health: 100,
        isWarning: false
    }, {
        name: '广东（深圳四区）',
        city: '深圳',
        idc: 1,
        host: 207,
        sw: 53,
        health: 100,
        isWarning: false
    }]
}, {
    name: '上海市',
    children: [{
        name: '上海一区',
        city: '上海市',
        idc: 3,
        host: 159,
        sw: 53,
        health: 100,
        isWarning: false
    }, {
        name: '宝信（上海一区）',
        city: '上海市',
        idc: 0,
        host: 6,
        sw: 16,
        health: 100,
        isWarning: false
    }, {
        name: '上海有孚教育专区',
        city: '上海市',
        idc: 0,
        host: 9,
        sw: 2,
        health: 100,
        isWarning: false
    }]
}, {
    name: '新疆',
    children: [{
        name: '新疆（乌鲁木齐一区）',
        city: '乌鲁木齐',
        idc: 1,
        host: 13,
        sw: 8,
        health: 100,
        isWarning: false
    }]
}, {
    name: '广西',
    children: [{
        name: '广西（南宁一区）',
        city: '南宁',
        idc: 2,
        host: 50,
        sw: 15,
        health: 100,
        isWarning: false
    }]
}, {
    name: '内蒙古',
    children: [{
        name: '内蒙古（呼和浩特一区）',
        city: '呼和浩特',
        idc: 1,
        host: 19,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '内蒙古（启正一区）',
        city: '启正',
        idc: 0,
        host: 13,
        sw: 15,
        health: 100,
        isWarning: false
    }]
}, {
    name: '江苏省',
    children: [{
        name: '江苏（南京二区）',
        city: '南京',
        idc: 2,
        host: 15,
        sw: 7,
        health: 100,
        isWarning: false
    }, {
        name: '江苏（凤凰云）',
        city: '南京',
        idc: 0,
        host: 27,
        sw: 4,
        health: 100,
        isWarning: false
    }, {
        name: '江苏（镇江一区）',
        city: '镇江',
        idc: 3,
        host: 20,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '移动（扬州一区）',
        city: '扬州',
        idc: 0,
        host: 8,
        sw: 0,
        health: 100,
        isWarning: false
    }, {
        name: '江苏（南通一区）',
        city: '南通',
        idc: 2,
        host: 13,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '江苏（无锡一区）',
        city: '无锡',
        idc: 1,
        host: 17,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '江苏（泰州一区）',
        city: '泰州',
        idc: 0,
        host: 22,
        sw: 7,
        health: 100,
        isWarning: false
    }, {
        name: '江苏（苏州二区）',
        city: '苏州',
        idc: 1,
        host: 11,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '移动（淮安一区）',
        city: '淮安',
        idc: 0,
        host: 8,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '江苏（苏州一区）',
        city: '苏州',
        idc: 1,
        host: 38,
        sw: 10,
        health: 100,
        isWarning: false
    }, {
        name: '江苏（常州一区）',
        city: '常州',
        idc: 1,
        host: 24,
        sw: 7,
        health: 100,
        isWarning: false
    }, {
        name: '江苏（南京一区）',
        city: '南京',
        idc: 4,
        host: 78,
        sw: 22,
        health: 100,
        isWarning: false
    }]
}, {
    name: '云南省',
    children: [{
        name: '云南（昆明一区）',
        city: '昆明',
        idc: 2,
        host: 28,
        sw: 15,
        health: 100,
        isWarning: false
    }, {
        name: '南天云（昆明一区）',
        city: '昆明',
        idc: 1,
        host: 12,
        sw: 5,
        health: 100,
        isWarning: false
    }]
}, {
    name: '天津市',
    children: [{
        name: '天津一区',
        city: '天津市',
        idc: 3,
        host: 35,
        sw: 15,
        health: 100,
        isWarning: false
    }]
}, {
    name: '宁夏',
    children: [{
        name: '宁夏（银川一区）',
        city: '银川',
        idc: 1,
        host: 13,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '宁夏（石嘴山一区）',
        city: '石嘴山',
        idc: 0,
        host: 17,
        sw: 3,
        health: 100,
        isWarning: false
    }]
}, {
    name: '湖南省',
    children: [{
        name: '联通（岳阳一区）',
        city: '岳阳',
        idc: 0,
        host: 13,
        sw: 0,
        health: 100,
        isWarning: false
    }, {
        name: '湖南（长沙一区）',
        city: '长沙',
        idc: 2,
        host: 28,
        sw: 14,
        health: 100,
        isWarning: false
    }, {
        name: '移动（株洲一区）',
        city: '株洲',
        idc: 0,
        host: 15,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '湖南（移动常德区）',
        city: '常德',
        idc: 0,
        host: 6,
        sw: 0,
        health: 100,
        isWarning: false
    }]
}, {
    name: '海南省',
    children: [{
        name: '海南（海口一区）',
        city: '海口',
        idc: 2,
        host: 16,
        sw: 8,
        health: 100,
        isWarning: false
    }]
}, {
    name: '辽宁省',
    children: [{
        name: '大连云数据（大连一区）',
        city: '大连',
        idc: 0,
        host: 13,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '辽宁（沈阳一区）',
        city: '沈阳',
        idc: 1,
        host: 12,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '辽宁（沈阳日报）',
        city: '沈阳',
        idc: 0,
        host: 4,
        sw: 7,
        health: 100,
        isWarning: false
    }]
}, {
    name: '浙江省',
    children: [{
        name: '浙江（杭州一区）',
        city: '杭州',
        idc: 4,
        host: 63,
        sw: 24,
        health: 100,
        isWarning: false
    }, {
        name: '海瑞（浙江一区）',
        city: '湖州',
        idc: 0,
        host: 0,
        sw: 0,
        health: 100,
        isWarning: false
    }, {
        name: '浙江（杭州二区）',
        city: '杭州',
        idc: 1,
        host: 5,
        sw: 7,
        health: 100,
        isWarning: false
    }, {
        name: '温州市工业互联网平台',
        city: '温州',
        idc: 0,
        host: 9,
        sw: 5,
        health: 100,
        isWarning: false
    }, {
        name: '浙江（温州一区）',
        city: '温州',
        idc: 1,
        host: 9,
        sw: 10,
        health: 100,
        isWarning: false
    }, {
        name: '浙江（宁波一区）',
        city: '宁波',
        idc: 1,
        host: 8,
        sw: 5,
        health: 100,
        isWarning: false
    }]
}, {
    name: '福建省',
    children: [{
        name: '福建（福州一区）',
        city: '福州',
        idc: 2,
        host: 36,
        sw: 15,
        health: 100,
        isWarning: false
    }, {
        name: '福建（厦门一区）',
        city: '厦门',
        idc: 1,
        host: 97,
        sw: 29,
        health: 100,
        isWarning: false
    }]
}, {
    name: '河北省',
    children: [{
        name: '河北（石家庄一区）',
        city: '石家庄',
        idc: 4,
        host: 51,
        sw: 18,
        health: 100,
        isWarning: false
    }, {
        name: '国信政务云专属云（廊坊一区）',
        city: '廊坊',
        idc: 0,
        host: 16,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '河北（保定电信）',
        city: '保定',
        idc: 0,
        host: 10,
        sw: 8,
        health: 100,
        isWarning: false
    }, {
        name: '鹿泉数字经济赋能平台',
        city: '石家庄',
        idc: 0,
        host: 12,
        sw: 8,
        health: 100,
        isWarning: false
    }]
}, {
    name: '贵州省',
    children: [{
        name: '贵州（贵阳一区）',
        city: '贵阳',
        idc: 2,
        host: 21,
        sw: 15,
        health: 100,
        isWarning: false
    }]
}, {
    name: '山西省',
    children: [{
        name: '山西（太原一区）',
        city: '太原',
        idc: 1,
        host: 39,
        sw: 15,
        health: 100,
        isWarning: false
    }, {
        name: '山西（太原二区）',
        city: '太原',
        idc: 1,
        host: 9,
        sw: 0,
        health: 100,
        isWarning: false
    }, {
        name: '山西（长治一区）',
        city: '长治',
        idc: 1,
        host: 9,
        sw: 5,
        health: 100,
        isWarning: false
    }]
}, {
    name: '黑龙江省',
    children: [{
        name: '黑龙江（哈尔滨一区）',
        city: '哈尔滨',
        idc: 1,
        host: 10,
        sw: 8,
        health: 100,
        isWarning: false
    }]
}
];